# Generated by Django 2.0.3 on 2018-03-17 14:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GGMLUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_count', models.IntegerField(default=0)),
                ('loss_count', models.IntegerField(default=0)),
                ('flair', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='props.Flair')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(max_length=5000)),
                ('date_added', models.DateTimeField(default=datetime.datetime(2018, 3, 17, 14, 17, 22, 21492))),
                ('taker_deadline', models.DateTimeField(blank=True, null=True)),
                ('resolution_date', models.DateTimeField()),
                ('limit_takers', models.IntegerField(default=10)),
                ('creator_won', models.BooleanField()),
                ('onion_hanger', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='prop',
            name='tag',
            field=models.ManyToManyField(to='props.Tag'),
        ),
        migrations.AddField(
            model_name='prop',
            name='takers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
