# Generated by Django 2.0.3 on 2018-03-17 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0002_auto_20180317_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prop',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 17, 14, 25, 56, 70073)),
        ),
        migrations.AlterField(
            model_name='prop',
            name='takers',
            field=models.ManyToManyField(to='props.GGMLUser'),
        ),
    ]
