# Generated by Django 2.0.3 on 2018-03-17 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0005_auto_20180317_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prop',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 17, 14, 44, 11, 967451)),
        ),
        migrations.AlterField(
            model_name='prop',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='props.Tag'),
        ),
    ]
