# Generated by Django 2.0.3 on 2018-03-17 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0006_auto_20180317_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prop',
            old_name='tag',
            new_name='tags',
        ),
        migrations.AlterField(
            model_name='prop',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 17, 14, 45, 6, 709295)),
        ),
    ]
