# Generated by Django 2.0.3 on 2018-03-17 15:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0010_auto_20180317_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='prop',
            name='creator',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to='props.GGMLUser'),
        ),
        migrations.AlterField(
            model_name='prop',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 17, 15, 3, 33, 261368)),
        ),
    ]
