# Generated by Django 2.0.3 on 2018-03-17 15:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0013_auto_20180317_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prop',
            name='creator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to='props.GGMLUser'),
        ),
        migrations.AlterField(
            model_name='prop',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 17, 15, 6, 25, 448172)),
        ),
    ]
